### PR TITLE
Translated full UI into German

### PR DESCRIPTION
**Pull request by digitalblossom**
Edit: After first pushing half the translation I've now gone ahead and translated everything (hence two commits)

### CODE REVIEW

**Comment by HACKERALERT** [comment]
Awesome, thank you so much!

**Comment by IHateTheProgrammingClass** [comment]
@HACKERALERT I'm looking forward to translate the GUI as well but I cannot find the strings.json in the resources that has been included in pull requests similar to this. It is present in other forks so I'm a bit confused.

**Comment by HACKERALERT** [comment]
@IHateTheProgrammingClass Since there's been a lot of changes since the initial translations, a lot of the UI changed. Thus, the old strings would not work well because a lot of them changed. At the moment, I haven't set up the current UI for translation yet, but I plan to do so soon. Give me a few days and I'll have strings.json ready for translation!

**Comment by IHateTheProgrammingClass** [comment]
Thank you, looking forward to it!

**Comment by HACKERALERT** [comment]
Thank you :) I'll ping you when I have everything ready.

**Comment by HACKERALERT** [comment]
It might take longer than I expected to get things set up because I'm moving the UI parts around a little. I'll keep you tuned, but it might be a week or two until I'll have things ready!

**Comment by IHateTheProgrammingClass** [comment]
@HACKERALERT I'm not trying to urge you or anything, take your time but I would like to ask you approximately how much time until this would be available? Thank you.

**Comment by HACKERALERT** [comment]
I'm actually not sure if I will be translating the main UI anymore, since the UI is pretty simple and I would need to manage a translation file which would use up more of my time than I would like. I think having the main readme translated is enough for anyone to understand the project, and a quick google translate via camera should be enough for a user to see it in any language.

**Comment by HACKERALERT** [comment]
I'll still have to see though, since I'm looking for new UI libraries and things may change.

**Pull request merged**
