### PR TITLE
Update portuguese.md

### PR DESCRIPTION
**Pull request by Rayserzor**
Update the translation from the ##Linux section.

### CODE REVIEW

**Comment by HACKERALERT** [comment]
Let me get some other things done, then I'll merge it. Thanks for the help!

**Comment by HACKERALERT** [comment]
Also, I think you request on the Mint forums to have Picocrypt added. Nice! Please let them know that they can contact me via this PR if they would like to talk to me directly (I don't use Linux so I don't find the need to sign up for a forum account).

**Comment by Rayserzor** [comment]
> Also, I think you requested on the Mint forums to have Picocrypt added. Nice! Please let them know that they can contact me via comments in this PR thread if they would like to talk to me directly (I don't use Linux so I don't find the need to sign up for a forum account).

They said: "That depends on the folks who manage the Ubuntu repos."

**Comment by HACKERALERT** [comment]
Indeed. Although since Picocrypt has a native .deb, if someone is willing and capable, they can push it to the official Debian repos which is the same as the official Ubuntu and Mint repos. It requires a Debian maintainer to do and seems quite complex, but if done correctly, Picocrypt will be available in future Debian-based distros with a simple `sudo apt install picocrypt`. However, the process is too complex in my opinion so I won't initiate the process myself and will let someone else do it, given that there are already three viable ways to run Picocrypt on Linux.

**Pull request merged**
