### PR TITLE
Italian translation of readme.md

### PR DESCRIPTION
**Pull request by Minibus93**

### CODE REVIEW

**Comment by HACKERALERT** [comment]
Thank you!

**Comment by HACKERALERT** [comment]
@Minibus93 One question, how do you say "Italian" in Italian? Google says italiana is feminine and italiano is masculine, but English doesn't have genders on objects so I'm confused. I think it's Italiano but I'm not sure. Basically, I want to link to your translation on the main page like with the others:
Screenshot (255)

**Comment by Minibus93** [comment]
Yes, in this specific use case the correct form it's "Italiano".

You did good :D

**Comment by HACKERALERT** [comment]
LOL, nice. I guess my rudimentary French made me choose masculine correctly.

**Comment by Minibus93** [comment]
On a side note, I noticed some very small error, mostly misspelling, I'd like to fix.
If it's ok for you I'll probably do it right now.

I also forgot to translate the line for the Hungarian translator and forgot to ask you If I should've add a line already in italian for myself so that you could then modify the original (english) readme.md

**Comment by HACKERALERT** [comment]
Sure, make another pull request with the fix(es). Also, add your name in for Italian and I'll do it on the English readme as well.

**Pull request merged**
